# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

default.if.null <- function(x, default_value) {
    .Call('ravro_default_if_null', PACKAGE = 'ravro', x, default_value)
}

fill.with.NAs.if.short <- function(x, nc) {
    .Call('ravro_NAs_if_short', PACKAGE = 'ravro', x, nc)
}

